### ISSUE TITLE
A Typo

### ISSUE THREAD

**Issue by shivanshs9** [Eight-Infotech/website#1]
@subodhk01 lol, it's Hibernate :joy: 

https://github.com/Eight-Infotech/website/blob/c0283b9c80dfcd115ae16039799dfc2fd0390485/index.html#L437

**Comment by subodhk01** [comment]
😂Mujhe toh pata bhi nhi hai hota kya hai

**Comment by subodhk01** [comment]
Fixed BTW ✌🏻
